/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.FrontEnd;

import com.mycompany.BackEnd.TrainerRole;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author seifs
 */
public class CancelRegistrationPage extends javax.swing.JFrame {

    /**
     * Creates new form CancelRegistrationPage
     */
    public CancelRegistrationPage() {
        initComponents();setVisible(true);
        setSize(new Dimension(436, 250));
        setContentPane(regirsterPanel);
        setTitle("Cancel Registration");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regirsterPanel = new javax.swing.JPanel();
        ClassIDText = new javax.swing.JTextField();
        memberIDLabel = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        cancelRegisterButton = new javax.swing.JButton();
        ClassIDLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClassIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassIDTextActionPerformed(evt);
            }
        });

        memberIDLabel.setBackground(new java.awt.Color(0, 153, 51));
        memberIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        memberIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        memberIDLabel.setText("Member ID");
        memberIDLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        memberIDLabel.setName(""); // NOI18N
        memberIDLabel.setOpaque(true);

        IDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextActionPerformed(evt);
            }
        });

        cancelRegisterButton.setBackground(new java.awt.Color(153, 153, 153));
        cancelRegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelRegisterButton.setText("Cancel Registeration");
        cancelRegisterButton.setBorder(null);
        cancelRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRegisterButtonActionPerformed(evt);
            }
        });

        ClassIDLabel.setBackground(new java.awt.Color(0, 153, 51));
        ClassIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        ClassIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClassIDLabel.setText("Class ID");
        ClassIDLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ClassIDLabel.setName(""); // NOI18N
        ClassIDLabel.setOpaque(true);

        javax.swing.GroupLayout regirsterPanelLayout = new javax.swing.GroupLayout(regirsterPanel);
        regirsterPanel.setLayout(regirsterPanelLayout);
        regirsterPanelLayout.setHorizontalGroup(
            regirsterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regirsterPanelLayout.createSequentialGroup()
                .addGroup(regirsterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(regirsterPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(cancelRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(regirsterPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(regirsterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(memberIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(ClassIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(regirsterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDText, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(ClassIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );
        regirsterPanelLayout.setVerticalGroup(
            regirsterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regirsterPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(regirsterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(regirsterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cancelRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regirsterPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regirsterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClassIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassIDTextActionPerformed

    private void IDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextActionPerformed

    private void cancelRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRegisterButtonActionPerformed
        // TODO add your handling code here:
        TrainerRole trainerRoleForPage = TrainerRolePage.trainerRole;
        String memberId = IDText.getText();
        String classId = ClassIDText.getText();
        if (memberId.isEmpty() || classId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields", "Message",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            if (trainerRoleForPage.cancelRegistration(memberId, classId)) {
                trainerRoleForPage.logout();
                JOptionPane.showMessageDialog(null,
                        "The Member with Id = " + memberId + " has been unregisterd from class " + classId);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "The Class has no member with id = " + memberId,
                        "Message",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_cancelRegisterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelRegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelRegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelRegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelRegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelRegistrationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClassIDLabel;
    private javax.swing.JTextField ClassIDText;
    private javax.swing.JTextField IDText;
    private javax.swing.JButton cancelRegisterButton;
    private javax.swing.JLabel memberIDLabel;
    private javax.swing.JPanel regirsterPanel;
    // End of variables declaration//GEN-END:variables
}
