/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.FrontEnd;

import com.mycompany.BackEnd.AdminRole;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Etijah
 */
public class RemoveTrainerPage extends javax.swing.JFrame {

    /**
     * Creates new form RemoveTrainerPage
     */
    public RemoveTrainerPage() {
        initComponents();
        setVisible(true);
        setSize(new Dimension(420, 146));
        setContentPane(RemowTrainer);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Remove Trainer");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RemowTrainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RemoveTrainerText = new javax.swing.JTextField();
        Remov = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 153, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trainer Id");
        jLabel1.setOpaque(true);

        Remov.setBackground(new java.awt.Color(153, 153, 153));
        Remov.setForeground(new java.awt.Color(255, 255, 255));
        Remov.setText("Remove");
        Remov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RemowTrainerLayout = new javax.swing.GroupLayout(RemowTrainer);
        RemowTrainer.setLayout(RemowTrainerLayout);
        RemowTrainerLayout.setHorizontalGroup(
            RemowTrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemowTrainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RemowTrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Remov, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveTrainerText, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        RemowTrainerLayout.setVerticalGroup(
            RemowTrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemowTrainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(RemowTrainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveTrainerText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Remov, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RemowTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RemowTrainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovActionPerformed
        String trainerId = RemoveTrainerText.getText();
        AdminRole AdminRoleForPage = AdminRolePage.adminRole;
        int sizeBefore = AdminRoleForPage.getListOfTrainers().size();
        AdminRoleForPage.removeTrainer(trainerId);
        int sizeAfter = AdminRoleForPage.getListOfTrainers().size();
        if (sizeBefore == sizeAfter)
            JOptionPane.showMessageDialog(RemowTrainer, "The Trainer with Id = " + trainerId + " doesn't exists!", "Massage", JOptionPane.WARNING_MESSAGE);
        else {
            AdminRoleForPage.logout();
            JOptionPane.showMessageDialog(RemowTrainer, "The Trainer with Id = " + trainerId + " has been deleted ");
            setVisible(false);
        }
    }//GEN-LAST:event_RemovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveTrainerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveTrainerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveTrainerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveTrainerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveTrainerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Remov;
    private javax.swing.JTextField RemoveTrainerText;
    private javax.swing.JPanel RemowTrainer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
