/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.FrontEnd;

import com.mycompany.BackEnd.TrainerRole;
import java.awt.Dimension;

/**
 *
 * @author seifs
 */
public class TrainerRolePage extends javax.swing.JFrame {

    static TrainerRole trainerRole = new TrainerRole();

    /**
     * Creates new form TrainerRolePage
     */
    public TrainerRolePage() {
        initComponents();
        setVisible(true);
        setSize(new Dimension(443, 500));
        setContentPane(trainerRolePanel);
        setTitle("Trainer Role");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainerRolePanel = new javax.swing.JPanel();
        addMember = new javax.swing.JButton();
        viewMembers = new javax.swing.JButton();
        addClass = new javax.swing.JButton();
        viewClasses = new javax.swing.JButton();
        registerMemberforClass = new javax.swing.JButton();
        cancelRegistration = new javax.swing.JButton();
        viewRegistrations = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addMember.setBackground(new java.awt.Color(0, 153, 0));
        addMember.setForeground(new java.awt.Color(255, 255, 255));
        addMember.setText("Add Member");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        viewMembers.setBackground(new java.awt.Color(0, 153, 0));
        viewMembers.setForeground(new java.awt.Color(255, 255, 255));
        viewMembers.setText("View Members");
        viewMembers.setToolTipText("");
        viewMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMembersActionPerformed(evt);
            }
        });

        addClass.setBackground(new java.awt.Color(0, 153, 0));
        addClass.setForeground(new java.awt.Color(255, 255, 255));
        addClass.setText("Add Class");
        addClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassActionPerformed(evt);
            }
        });

        viewClasses.setBackground(new java.awt.Color(0, 153, 0));
        viewClasses.setForeground(new java.awt.Color(255, 255, 255));
        viewClasses.setText("View Classes");
        viewClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewClassesActionPerformed(evt);
            }
        });

        registerMemberforClass.setBackground(new java.awt.Color(0, 153, 0));
        registerMemberforClass.setForeground(new java.awt.Color(255, 255, 255));
        registerMemberforClass.setText("Register Member for Class");
        registerMemberforClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMemberforClassActionPerformed(evt);
            }
        });

        cancelRegistration.setBackground(new java.awt.Color(0, 153, 0));
        cancelRegistration.setForeground(new java.awt.Color(255, 255, 255));
        cancelRegistration.setText("Cancel Registration");
        cancelRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRegistrationActionPerformed(evt);
            }
        });

        viewRegistrations.setBackground(new java.awt.Color(0, 153, 0));
        viewRegistrations.setForeground(new java.awt.Color(255, 255, 255));
        viewRegistrations.setText("View Registrations");
        viewRegistrations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRegistrationsActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 153, 0));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trainerRolePanelLayout = new javax.swing.GroupLayout(trainerRolePanel);
        trainerRolePanel.setLayout(trainerRolePanelLayout);
        trainerRolePanelLayout.setHorizontalGroup(
            trainerRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainerRolePanelLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(trainerRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerMemberforClass, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(viewClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewRegistrations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 138, Short.MAX_VALUE))
        );
        trainerRolePanelLayout.setVerticalGroup(
            trainerRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainerRolePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(addMember, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addClass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerMemberforClass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewRegistrations, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trainerRolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trainerRolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        // TODO add your handling code here:
        AddMemberPage a = new AddMemberPage();
    }//GEN-LAST:event_addMemberActionPerformed

    private void viewMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMembersActionPerformed
        // TODO add your handling code here:
        ViewMembersPage v = new ViewMembersPage();
    }//GEN-LAST:event_viewMembersActionPerformed

    private void addClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassActionPerformed
        // TODO add your handling code here:
        AddClassPage a = new AddClassPage();
    }//GEN-LAST:event_addClassActionPerformed

    private void viewClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewClassesActionPerformed
        // TODO add your handling code here:
        ViewClassPage v = new ViewClassPage();
    }//GEN-LAST:event_viewClassesActionPerformed

    private void registerMemberforClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMemberforClassActionPerformed
        // TODO add your handling code here:
        registerMemberforClassPage rm = new registerMemberforClassPage();
    }//GEN-LAST:event_registerMemberforClassActionPerformed

    private void cancelRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRegistrationActionPerformed
        // TODO add your handling code here:
        CancelRegistrationPage cr = new CancelRegistrationPage();
    }//GEN-LAST:event_cancelRegistrationActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        trainerRole.logout();
        MainWindow mainWindow = new MainWindow();
        setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    private void viewRegistrationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRegistrationsActionPerformed
        // TODO add your handling code here:
        ViewRegistrationPage vr = new ViewRegistrationPage();
    }//GEN-LAST:event_viewRegistrationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainerRolePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainerRolePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainerRolePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainerRolePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainerRolePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClass;
    private javax.swing.JButton addMember;
    private javax.swing.JButton cancelRegistration;
    private javax.swing.JButton logout;
    private javax.swing.JButton registerMemberforClass;
    private javax.swing.JPanel trainerRolePanel;
    private javax.swing.JButton viewClasses;
    private javax.swing.JButton viewMembers;
    private javax.swing.JButton viewRegistrations;
    // End of variables declaration//GEN-END:variables
}
